<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. Visitor Sessions Table
        Schema::create('visitor_sessions', function (Blueprint $table) {
            $table->id();
            $table->string('session_id')->unique(); // UUID generated by client
            $table->string('ip_hash')->nullable(); // Privacy-safe hashed IP
            $table->text('user_agent')->nullable();
            $table->string('device_type')->default('mobile'); // mobile, tablet, desktop
            $table->string('os')->default('Unknown'); // iOS, Android, Windows, macOS, Linux
            $table->string('browser')->default('Unknown'); // Safari, Chrome, Edge, Firefox
            $table->string('referrer_source')->default('Direct'); // Instagram, TikTok, Google Maps, QR Table, WhatsApp, Direct
            $table->string('location_city')->default('Jakarta');
            $table->string('customer_phone')->nullable(); // Linked when user orders or enters phone
            $table->boolean('is_active')->default(true);
            $table->timestamp('last_active_at')->useCurrent();
            $table->timestamps();
        });

        // 2. Visitor Interaction & Telemetry Events Table
        Schema::create('visitor_events', function (Blueprint $table) {
            $table->id();
            $table->foreignId('visitor_session_id')->constrained('visitor_sessions')->onDelete('cascade');
            $table->string('event_type'); // page_view, qr_scan, menu_click, add_to_cart, checkout_start, order_complete, reservation_start
            $table->string('section_name')->default('home'); // hero, menu, reservation, order, events, about, kds
            $table->json('metadata')->nullable(); // table_number, menu_id, menu_name, price, etc.
            $table->timestamp('created_at')->useCurrent();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('visitor_events');
        Schema::dropIfExists('visitor_sessions');
    }
};
